name: Docker Compose 2
#description: Do something useful.
metadata:
#  keywords:
#    - docker-compose-2
#  guide: https://docs.quarkiverse.io/docker-compose-2/dev/ # To create and publish this guide, see https://github.com/quarkiverse/quarkiverse/wiki#documenting-your-extension
#  categories:
#    - "miscellaneous"
#  status: "preview"
